---
version: 2
updates:
  - package-ecosystem: "github-actions"
    assignees:
      - "kernelsam"
    cooldown:
      default-days: 21
      exclude:
        - "senzing-factory/*"
    directory: "/"
    groups:
      senzing-factory:
        patterns:
          - "senzing-factory/*"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    assignees:
      - "barrycaceres"
    cooldown:
      default-days: 21
      exclude:
        - "com.senzing:*"
    directory: "/"
    schedule:
      interval: "daily"
